/*
 *
 * Copyright (c) 2025 Infenia Technologies Pvt. Ltd.
 *
 * This file is part of the EasyMarry Application.
 *
 * Licensed under the Infenia license; you may not use this file except
 * in compliance with the License. Unauthorized copying of this file,
 * via any medium is strictly prohibited.
 *
 * For more information, contact arun@infenia.com
 *
 */

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
    `kotlin-dsl`
    idea
}

repositories {
    // Use the plugin portal to apply community plugins in convention plugins.
    mavenCentral()
    gradlePluginPortal()
}

// Version constants - will be migrated to version catalog for projects
val springBootVersion = "3.4.5"
val springDependencyManagementVersion = "1.1.7"
val spotlessVersion = "7.0.3"
val asciiDoctorVersion = "4.0.4"
val lombokVersion = "8.13.1"
val graalvmBuildToolsVersion = "0.10.3"
val cyclonedxVersion = "2.2.0"
val spotBugsVersion = "6.0.27"
val owaspDependencycheck = "12.1.3"
val sonarqubeVersion = "6.2.0.5505"

dependencies {
    implementation("org.springframework.boot:spring-boot-gradle-plugin:$springBootVersion")
    implementation("io.spring.gradle:dependency-management-plugin:$springDependencyManagementVersion")
    implementation("org.asciidoctor:asciidoctor-gradle-jvm:$asciiDoctorVersion")
    implementation("com.diffplug.spotless:spotless-plugin-gradle:$spotlessVersion")
    implementation("io.freefair.gradle:lombok-plugin:$lombokVersion")
    implementation("org.graalvm.buildtools:native-gradle-plugin:$graalvmBuildToolsVersion")
    implementation("org.cyclonedx:cyclonedx-gradle-plugin:$cyclonedxVersion")
    implementation("com.github.spotbugs:com.github.spotbugs.gradle.plugin:$spotBugsVersion")
    implementation("org.owasp.dependencycheck:org.owasp.dependencycheck.gradle.plugin:$owaspDependencycheck")
    implementation("org.sonarqube:org.sonarqube.gradle.plugin:$sonarqubeVersion")
    implementation("org.springframework.boot:spring-boot-starter-cache")
    implementation("com.github.ben-manes.caffeine:caffeine")
}